apiVersion: v1
kind: Pod
metadata:
  name: made-ml-hw4-resources
  labels:
    app: fastapi-ml
spec:
  containers:
    - name: fastapi-ml
      image: cyrusmsk/online_inference:v1
      ports:
        - name: api
          containerPort: 8000
          protocol: TCP
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"