apiVersion: v1
kind: Pod
metadata:
  name: made-ml-hw4
  labels:
    app: fastapi-ml
spec:
  containers:
    - name: fastapi-ml
      image: cyrusmsk/online_inference:v1
      ports:
        - name: api
          containerPort: 8000
          protocol: TCP