input_data_path: "data/raw/train.csv"
output_data_path: "data/processed/predict.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
defaults:
  - feature_params: all_features